export const customSX = {
	".iekbcc0": {
		border: "0",
		boxSizing: "border-box",
		fontSize: "100%",
		lineHeight: "normal",
		margin: "0",
		padding: "0",
		textAlign: "left",
		verticalAlign: "baseline",
		WebkitTapHighlightColor: "transparent",
	},
	".iekbcc1": { listStyle: "none" },
	".iekbcc2": { quotes: "none" },
	".iekbcc2_before": { content: '""' },
	".iekbcc2_after": { content: '""' },
	".iekbcc3": { borderCollapse: "collapse", borderSpacing: "0" },
	".iekbcc4": {
		WebkitAppearance: "none",
		MozAppearance: "none",
		appearance: "none",
	},
	".iekbcc5": { outline: "none" },
	".iekbcc5___moz_placeholder": { opacity: "1" },
	".iekbcc5__ms_input_placeholder": { opacity: "1" },
	".iekbcc5__placeholder": { opacity: "1" },
	".iekbcc6": { backgroundColor: "transparent", color: "inherit" },
	".iekbcc7_disabled": { opacity: "1" },
	".iekbcc7___ms_expand": { display: "none" },
	".iekbcc8___ms_clear": { display: "none" },
	".iekbcc8___webkit_search_cancel_button": {
		WebkitAppearance: "none",
	},
	".iekbcc9": {
		background: "none",
		cursor: "pointer",
		textAlign: "left",
	},
	".iekbcca": { color: "inherit", textDecoration: "none" },
	".ju367v0": { alignItems: "flex-start" },
	".ju367v2": { alignItems: "flex-end" },
	".ju367v4": { alignItems: "center" },
	".ju367v6": { display: "none" },
	".ju367v8": { display: "block" },
	".ju367va": { display: "flex" },
	".ju367vc": { display: "inline" },
	".ju367ve": { alignSelf: "flex-start" },
	".ju367vf": { alignSelf: "flex-end" },
	".ju367vg": { alignSelf: "center" },
	".ju367vh": { backgroundSize: "cover" },
	".ju367vi": { borderRadius: "1px" },
	".ju367vj": { borderRadius: "6px" },
	".ju367vk": { borderRadius: "10px" },
	".ju367vl": { borderRadius: "13px" },
	".ju367vm": { borderRadius: "var(--rk-radii-actionButton)" },
	".ju367vn": { borderRadius: "var(--rk-radii-connectButton)" },
	".ju367vo": { borderRadius: "var(--rk-radii-menuButton)" },
	".ju367vp": { borderRadius: "var(--rk-radii-modal)" },
	".ju367vq": { borderRadius: "var(--rk-radii-modalMobile)" },
	".ju367vr": { borderRadius: "25%" },
	".ju367vs": { borderRadius: "9999px" },
	".ju367vt": { borderStyle: "solid" },
	".ju367vu": { borderWidth: "0px" },
	".ju367vv": { borderWidth: "1px" },
	".ju367vw": { borderWidth: "2px" },
	".ju367vx": { borderWidth: "4px" },
	".ju367vy": { cursor: "pointer" },
	".ju367vz": { flexDirection: "row" },
	".ju367v10": { flexDirection: "column" },
	".ju367v11": { fontFamily: "var(--rk-fonts-body)" },
	".ju367v12": { fontSize: "12px", lineHeight: "18px" },
	".ju367v13": { fontSize: "13px", lineHeight: "18px" },
	".ju367v14": { fontSize: "14px", lineHeight: "18px" },
	".ju367v15": { fontSize: "16px", lineHeight: "20px" },
	".ju367v16": { fontSize: "18px", lineHeight: "24px" },
	".ju367v17": { fontSize: "20px", lineHeight: "24px" },
	".ju367v18": { fontSize: "23px", lineHeight: "29px" },
	".ju367v19": { fontWeight: "400" },
	".ju367v1a": { fontWeight: "500" },
	".ju367v1b": { fontWeight: "600" },
	".ju367v1c": { fontWeight: "700" },
	".ju367v1d": { fontWeight: "800" },
	".ju367v1e": { gap: "0" },
	".ju367v1f": { gap: "1px" },
	".ju367v1g": { gap: "2px" },
	".ju367v1h": { gap: "3px" },
	".ju367v1i": { gap: "4px" },
	".ju367v1j": { gap: "5px" },
	".ju367v1k": { gap: "6px" },
	".ju367v1l": { gap: "8px" },
	".ju367v1m": { gap: "10px" },
	".ju367v1n": { gap: "12px" },
	".ju367v1o": { gap: "14px" },
	".ju367v1p": { gap: "16px" },
	".ju367v1q": { gap: "18px" },
	".ju367v1r": { gap: "20px" },
	".ju367v1s": { gap: "24px" },
	".ju367v1t": { gap: "28px" },
	".ju367v1u": { gap: "32px" },
	".ju367v1v": { gap: "36px" },
	".ju367v1w": { gap: "44px" },
	".ju367v1x": { gap: "64px" },
	".ju367v1y": { gap: "-1px" },
	".ju367v1z": { height: "1px" },
	".ju367v20": { height: "2px" },
	".ju367v21": { height: "4px" },
	".ju367v22": { height: "8px" },
	".ju367v23": { height: "12px" },
	".ju367v24": { height: "20px" },
	".ju367v25": { height: "24px" },
	".ju367v26": { height: "28px" },
	".ju367v27": { height: "30px" },
	".ju367v28": { height: "32px" },
	".ju367v29": { height: "34px" },
	".ju367v2a": { height: "36px" },
	".ju367v2b": { height: "40px" },
	".ju367v2c": { height: "44px" },
	".ju367v2d": { height: "48px" },
	".ju367v2e": { height: "54px" },
	".ju367v2f": { height: "60px" },
	".ju367v2g": { height: "200px" },
	".ju367v2h": { height: "100%" },
	".ju367v2i": { height: "max-content" },
	".ju367v2j": { justifyContent: "flex-start" },
	".ju367v2k": { justifyContent: "flex-end" },
	".ju367v2l": { justifyContent: "center" },
	".ju367v2m": { justifyContent: "space-between" },
	".ju367v2n": { justifyContent: "space-around" },
	".ju367v2o": { textAlign: "left" },
	".ju367v2p": { textAlign: "center" },
	".ju367v2q": { textAlign: "inherit" },
	".ju367v2r": { marginBottom: "0" },
	".ju367v2s": { marginBottom: "1px" },
	".ju367v2t": { marginBottom: "2px" },
	".ju367v2u": { marginBottom: "3px" },
	".ju367v2v": { marginBottom: "4px" },
	".ju367v2w": { marginBottom: "5px" },
	".ju367v2x": { marginBottom: "6px" },
	".ju367v2y": { marginBottom: "8px" },
	".ju367v2z": { marginBottom: "10px" },
	".ju367v30": { marginBottom: "12px" },
	".ju367v31": { marginBottom: "14px" },
	".ju367v32": { marginBottom: "16px" },
	".ju367v33": { marginBottom: "18px" },
	".ju367v34": { marginBottom: "20px" },
	".ju367v35": { marginBottom: "24px" },
	".ju367v36": { marginBottom: "28px" },
	".ju367v37": { marginBottom: "32px" },
	".ju367v38": { marginBottom: "36px" },
	".ju367v39": { marginBottom: "44px" },
	".ju367v3a": { marginBottom: "64px" },
	".ju367v3b": { marginBottom: "-1px" },
	".ju367v3c": { marginLeft: "0" },
	".ju367v3d": { marginLeft: "1px" },
	".ju367v3e": { marginLeft: "2px" },
	".ju367v3f": { marginLeft: "3px" },
	".ju367v3g": { marginLeft: "4px" },
	".ju367v3h": { marginLeft: "5px" },
	".ju367v3i": { marginLeft: "6px" },
	".ju367v3j": { marginLeft: "8px" },
	".ju367v3k": { marginLeft: "10px" },
	".ju367v3l": { marginLeft: "12px" },
	".ju367v3m": { marginLeft: "14px" },
	".ju367v3n": { marginLeft: "16px" },
	".ju367v3o": { marginLeft: "18px" },
	".ju367v3p": { marginLeft: "20px" },
	".ju367v3q": { marginLeft: "24px" },
	".ju367v3r": { marginLeft: "28px" },
	".ju367v3s": { marginLeft: "32px" },
	".ju367v3t": { marginLeft: "36px" },
	".ju367v3u": { marginLeft: "44px" },
	".ju367v3v": { marginLeft: "64px" },
	".ju367v3w": { marginLeft: "-1px" },
	".ju367v3x": { marginRight: "0" },
	".ju367v3y": { marginRight: "1px" },
	".ju367v3z": { marginRight: "2px" },
	".ju367v40": { marginRight: "3px" },
	".ju367v41": { marginRight: "4px" },
	".ju367v42": { marginRight: "5px" },
	".ju367v43": { marginRight: "6px" },
	".ju367v44": { marginRight: "8px" },
	".ju367v45": { marginRight: "10px" },
	".ju367v46": { marginRight: "12px" },
	".ju367v47": { marginRight: "14px" },
	".ju367v48": { marginRight: "16px" },
	".ju367v49": { marginRight: "18px" },
	".ju367v4a": { marginRight: "20px" },
	".ju367v4b": { marginRight: "24px" },
	".ju367v4c": { marginRight: "28px" },
	".ju367v4d": { marginRight: "32px" },
	".ju367v4e": { marginRight: "36px" },
	".ju367v4f": { marginRight: "44px" },
	".ju367v4g": { marginRight: "64px" },
	".ju367v4h": { marginRight: "-1px" },
	".ju367v4i": { marginTop: "0" },
	".ju367v4j": { marginTop: "1px" },
	".ju367v4k": { marginTop: "2px" },
	".ju367v4l": { marginTop: "3px" },
	".ju367v4m": { marginTop: "4px" },
	".ju367v4n": { marginTop: "5px" },
	".ju367v4o": { marginTop: "6px" },
	".ju367v4p": { marginTop: "8px" },
	".ju367v4q": { marginTop: "10px" },
	".ju367v4r": { marginTop: "12px" },
	".ju367v4s": { marginTop: "14px" },
	".ju367v4t": { marginTop: "16px" },
	".ju367v4u": { marginTop: "18px" },
	".ju367v4v": { marginTop: "20px" },
	".ju367v4w": { marginTop: "24px" },
	".ju367v4x": { marginTop: "28px" },
	".ju367v4y": { marginTop: "32px" },
	".ju367v4z": { marginTop: "36px" },
	".ju367v50": { marginTop: "44px" },
	".ju367v51": { marginTop: "64px" },
	".ju367v52": { marginTop: "-1px" },
	".ju367v53": { maxWidth: "1px" },
	".ju367v54": { maxWidth: "2px" },
	".ju367v55": { maxWidth: "4px" },
	".ju367v56": { maxWidth: "8px" },
	".ju367v57": { maxWidth: "12px" },
	".ju367v58": { maxWidth: "20px" },
	".ju367v59": { maxWidth: "24px" },
	".ju367v5a": { maxWidth: "28px" },
	".ju367v5b": { maxWidth: "30px" },
	".ju367v5c": { maxWidth: "32px" },
	".ju367v5d": { maxWidth: "34px" },
	".ju367v5e": { maxWidth: "36px" },
	".ju367v5f": { maxWidth: "40px" },
	".ju367v5g": { maxWidth: "44px" },
	".ju367v5h": { maxWidth: "48px" },
	".ju367v5i": { maxWidth: "54px" },
	".ju367v5j": { maxWidth: "60px" },
	".ju367v5k": { maxWidth: "200px" },
	".ju367v5l": { maxWidth: "100%" },
	".ju367v5m": { maxWidth: "max-content" },
	".ju367v5n": { minWidth: "1px" },
	".ju367v5o": { minWidth: "2px" },
	".ju367v5p": { minWidth: "4px" },
	".ju367v5q": { minWidth: "8px" },
	".ju367v5r": { minWidth: "12px" },
	".ju367v5s": { minWidth: "20px" },
	".ju367v5t": { minWidth: "24px" },
	".ju367v5u": { minWidth: "28px" },
	".ju367v5v": { minWidth: "30px" },
	".ju367v5w": { minWidth: "32px" },
	".ju367v5x": { minWidth: "34px" },
	".ju367v5y": { minWidth: "36px" },
	".ju367v5z": { minWidth: "40px" },
	".ju367v60": { minWidth: "44px" },
	".ju367v61": { minWidth: "48px" },
	".ju367v62": { minWidth: "54px" },
	".ju367v63": { minWidth: "60px" },
	".ju367v64": { minWidth: "200px" },
	".ju367v65": { minWidth: "100%" },
	".ju367v66": { minWidth: "max-content" },
	".ju367v67": { overflow: "hidden" },
	".ju367v68": { paddingBottom: "0" },
	".ju367v69": { paddingBottom: "1px" },
	".ju367v6a": { paddingBottom: "2px" },
	".ju367v6b": { paddingBottom: "3px" },
	".ju367v6c": { paddingBottom: "4px" },
	".ju367v6d": { paddingBottom: "5px" },
	".ju367v6e": { paddingBottom: "6px" },
	".ju367v6f": { paddingBottom: "8px" },
	".ju367v6g": { paddingBottom: "10px" },
	".ju367v6h": { paddingBottom: "12px" },
	".ju367v6i": { paddingBottom: "14px" },
	".ju367v6j": { paddingBottom: "16px" },
	".ju367v6k": { paddingBottom: "18px" },
	".ju367v6l": { paddingBottom: "20px" },
	".ju367v6m": { paddingBottom: "24px" },
	".ju367v6n": { paddingBottom: "28px" },
	".ju367v6o": { paddingBottom: "32px" },
	".ju367v6p": { paddingBottom: "36px" },
	".ju367v6q": { paddingBottom: "44px" },
	".ju367v6r": { paddingBottom: "64px" },
	".ju367v6s": { paddingBottom: "-1px" },
	".ju367v6t": { paddingLeft: "0" },
	".ju367v6u": { paddingLeft: "1px" },
	".ju367v6v": { paddingLeft: "2px" },
	".ju367v6w": { paddingLeft: "3px" },
	".ju367v6x": { paddingLeft: "4px" },
	".ju367v6y": { paddingLeft: "5px" },
	".ju367v6z": { paddingLeft: "6px" },
	".ju367v70": { paddingLeft: "8px" },
	".ju367v71": { paddingLeft: "10px" },
	".ju367v72": { paddingLeft: "12px" },
	".ju367v73": { paddingLeft: "14px" },
	".ju367v74": { paddingLeft: "16px" },
	".ju367v75": { paddingLeft: "18px" },
	".ju367v76": { paddingLeft: "20px" },
	".ju367v77": { paddingLeft: "24px" },
	".ju367v78": { paddingLeft: "28px" },
	".ju367v79": { paddingLeft: "32px" },
	".ju367v7a": { paddingLeft: "36px" },
	".ju367v7b": { paddingLeft: "44px" },
	".ju367v7c": { paddingLeft: "64px" },
	".ju367v7d": { paddingLeft: "-1px" },
	".ju367v7e": { paddingRight: "0" },
	".ju367v7f": { paddingRight: "1px" },
	".ju367v7g": { paddingRight: "2px" },
	".ju367v7h": { paddingRight: "3px" },
	".ju367v7i": { paddingRight: "4px" },
	".ju367v7j": { paddingRight: "5px" },
	".ju367v7k": { paddingRight: "6px" },
	".ju367v7l": { paddingRight: "8px" },
	".ju367v7m": { paddingRight: "10px" },
	".ju367v7n": { paddingRight: "12px" },
	".ju367v7o": { paddingRight: "14px" },
	".ju367v7p": { paddingRight: "16px" },
	".ju367v7q": { paddingRight: "18px" },
	".ju367v7r": { paddingRight: "20px" },
	".ju367v7s": { paddingRight: "24px" },
	".ju367v7t": { paddingRight: "28px" },
	".ju367v7u": { paddingRight: "32px" },
	".ju367v7v": { paddingRight: "36px" },
	".ju367v7w": { paddingRight: "44px" },
	".ju367v7x": { paddingRight: "64px" },
	".ju367v7y": { paddingRight: "-1px" },
	".ju367v7z": { paddingTop: "0" },
	".ju367v80": { paddingTop: "1px" },
	".ju367v81": { paddingTop: "2px" },
	".ju367v82": { paddingTop: "3px" },
	".ju367v83": { paddingTop: "4px" },
	".ju367v84": { paddingTop: "5px" },
	".ju367v85": { paddingTop: "6px" },
	".ju367v86": { paddingTop: "8px" },
	".ju367v87": { paddingTop: "10px" },
	".ju367v88": { paddingTop: "12px" },
	".ju367v89": { paddingTop: "14px" },
	".ju367v8a": { paddingTop: "16px" },
	".ju367v8b": { paddingTop: "18px" },
	".ju367v8c": { paddingTop: "20px" },
	".ju367v8d": { paddingTop: "24px" },
	".ju367v8e": { paddingTop: "28px" },
	".ju367v8f": { paddingTop: "32px" },
	".ju367v8g": { paddingTop: "36px" },
	".ju367v8h": { paddingTop: "44px" },
	".ju367v8i": { paddingTop: "64px" },
	".ju367v8j": { paddingTop: "-1px" },
	".ju367v8k": { position: "absolute" },
	".ju367v8l": { position: "fixed" },
	".ju367v8m": { position: "relative" },
	".ju367v8n": { right: "0" },
	".ju367v8o": { transition: "0.125s ease" },
	".ju367v8p": { transition: "transform 0.125s ease" },
	".ju367v8q": {
		WebkitUserSelect: "none",
		MozUserSelect: "none",
		MsUserSelect: "none",
		userSelect: "none",
	},
	".ju367v8r": { width: "1px" },
	".ju367v8s": { width: "2px" },
	".ju367v8t": { width: "4px" },
	".ju367v8u": { width: "8px" },
	".ju367v8v": { width: "12px" },
	".ju367v8w": { width: "20px" },
	".ju367v8x": { width: "24px" },
	".ju367v8y": { width: "28px" },
	".ju367v8z": { width: "30px" },
	".ju367v90": { width: "32px" },
	".ju367v91": { width: "34px" },
	".ju367v92": { width: "36px" },
	".ju367v93": { width: "40px" },
	".ju367v94": { width: "44px" },
	".ju367v95": { width: "48px" },
	".ju367v96": { width: "54px" },
	".ju367v97": { width: "60px" },
	".ju367v98": { width: "200px" },
	".ju367v99": { width: "100%" },
	".ju367v9a": { width: "max-content" },
	".ju367v9b": {
		WebkitBackdropFilter: "var(--rk-blurs-modalOverlay)",
		backdropFilter: "var(--rk-blurs-modalOverlay)",
	},
	".ju367v9c": { background: "var(--rk-colors-accentColor)" },
	".ju367v9d_hover": { background: "var(--rk-colors-accentColor)" },
	".ju367v9e_active": { background: "var(--rk-colors-accentColor)" },
	".ju367v9f": {
		background: "var(--rk-colors-accentColorForeground)",
	},
	".ju367v9g_hover": {
		background: "var(--rk-colors-accentColorForeground)",
	},
	".ju367v9h_active": {
		background: "var(--rk-colors-accentColorForeground)",
	},
	".ju367v9i": { background: "var(--rk-colors-actionButtonBorder)" },
	".ju367v9j_hover": {
		background: "var(--rk-colors-actionButtonBorder)",
	},
	".ju367v9k_active": {
		background: "var(--rk-colors-actionButtonBorder)",
	},
	".ju367v9l": {
		background: "var(--rk-colors-actionButtonBorderMobile)",
	},
	".ju367v9m_hover": {
		background: "var(--rk-colors-actionButtonBorderMobile)",
	},
	".ju367v9n_active": {
		background: "var(--rk-colors-actionButtonBorderMobile)",
	},
	".ju367v9o": {
		background: "var(--rk-colors-actionButtonSecondaryBackground)",
	},
	".ju367v9p_hover": {
		background: "var(--rk-colors-actionButtonSecondaryBackground)",
	},
	".ju367v9q_active": {
		background: "var(--rk-colors-actionButtonSecondaryBackground)",
	},
	".ju367v9r": { background: "var(--rk-colors-closeButton)" },
	".ju367v9s_hover": { background: "var(--rk-colors-closeButton)" },
	".ju367v9t_active": { background: "var(--rk-colors-closeButton)" },
	".ju367v9u": {
		background: "var(--rk-colors-closeButtonBackground)",
	},
	".ju367v9v_hover": {
		background: "var(--rk-colors-closeButtonBackground)",
	},
	".ju367v9w_active": {
		background: "var(--rk-colors-closeButtonBackground)",
	},
	".ju367v9x": {
		background: "var(--rk-colors-connectButtonBackground)",
	},
	".ju367v9y_hover": {
		background: "var(--rk-colors-connectButtonBackground)",
	},
	".ju367v9z_active": {
		background: "var(--rk-colors-connectButtonBackground)",
	},
	".ju367va0": {
		background: "var(--rk-colors-connectButtonBackgroundError)",
	},
	".ju367va1_hover": {
		background: "var(--rk-colors-connectButtonBackgroundError)",
	},
	".ju367va2_active": {
		background: "var(--rk-colors-connectButtonBackgroundError)",
	},
	".ju367va3": {
		background: "var(--rk-colors-connectButtonInnerBackground)",
	},
	".ju367va4_hover": {
		background: "var(--rk-colors-connectButtonInnerBackground)",
	},
	".ju367va5_active": {
		background: "var(--rk-colors-connectButtonInnerBackground)",
	},
	".ju367va6": { background: "var(--rk-colors-connectButtonText)" },
	".ju367va7_hover": {
		background: "var(--rk-colors-connectButtonText)",
	},
	".ju367va8_active": {
		background: "var(--rk-colors-connectButtonText)",
	},
	".ju367va9": {
		background: "var(--rk-colors-connectButtonTextError)",
	},
	".ju367vaa_hover": {
		background: "var(--rk-colors-connectButtonTextError)",
	},
	".ju367vab_active": {
		background: "var(--rk-colors-connectButtonTextError)",
	},
	".ju367vac": { background: "var(--rk-colors-connectionIndicator)" },
	".ju367vad_hover": {
		background: "var(--rk-colors-connectionIndicator)",
	},
	".ju367vae_active": {
		background: "var(--rk-colors-connectionIndicator)",
	},
	".ju367vaf": {
		background: "var(--rk-colors-downloadBottomCardBackground)",
	},
	".ju367vag_hover": {
		background: "var(--rk-colors-downloadBottomCardBackground)",
	},
	".ju367vah_active": {
		background: "var(--rk-colors-downloadBottomCardBackground)",
	},
	".ju367vai": {
		background: "var(--rk-colors-downloadTopCardBackground)",
	},
	".ju367vaj_hover": {
		background: "var(--rk-colors-downloadTopCardBackground)",
	},
	".ju367vak_active": {
		background: "var(--rk-colors-downloadTopCardBackground)",
	},
	".ju367val": { background: "var(--rk-colors-error)" },
	".ju367vam_hover": { background: "var(--rk-colors-error)" },
	".ju367van_active": { background: "var(--rk-colors-error)" },
	".ju367vao": { background: "var(--rk-colors-generalBorder)" },
	".ju367vap_hover": { background: "var(--rk-colors-generalBorder)" },
	".ju367vaq_active": {
		background: "var(--rk-colors-generalBorder)",
	},
	".ju367var": { background: "var(--rk-colors-generalBorderDim)" },
	".ju367vas_hover": {
		background: "var(--rk-colors-generalBorderDim)",
	},
	".ju367vat_active": {
		background: "var(--rk-colors-generalBorderDim)",
	},
	".ju367vau": { background: "var(--rk-colors-menuItemBackground)" },
	".ju367vav_hover": {
		background: "var(--rk-colors-menuItemBackground)",
	},
	".ju367vaw_active": {
		background: "var(--rk-colors-menuItemBackground)",
	},
	".ju367vax": { background: "var(--rk-colors-modalBackdrop)" },
	".ju367vay_hover": { background: "var(--rk-colors-modalBackdrop)" },
	".ju367vaz_active": {
		background: "var(--rk-colors-modalBackdrop)",
	},
	".ju367vb0": { background: "var(--rk-colors-modalBackground)" },
	".ju367vb1_hover": {
		background: "var(--rk-colors-modalBackground)",
	},
	".ju367vb2_active": {
		background: "var(--rk-colors-modalBackground)",
	},
	".ju367vb3": { background: "var(--rk-colors-modalBorder)" },
	".ju367vb4_hover": { background: "var(--rk-colors-modalBorder)" },
	".ju367vb5_active": { background: "var(--rk-colors-modalBorder)" },
	".ju367vb6": { background: "var(--rk-colors-modalText)" },
	".ju367vb7_hover": { background: "var(--rk-colors-modalText)" },
	".ju367vb8_active": { background: "var(--rk-colors-modalText)" },
	".ju367vb9": { background: "var(--rk-colors-modalTextDim)" },
	".ju367vba_hover": { background: "var(--rk-colors-modalTextDim)" },
	".ju367vbb_active": { background: "var(--rk-colors-modalTextDim)" },
	".ju367vbc": { background: "var(--rk-colors-modalTextSecondary)" },
	".ju367vbd_hover": {
		background: "var(--rk-colors-modalTextSecondary)",
	},
	".ju367vbe_active": {
		background: "var(--rk-colors-modalTextSecondary)",
	},
	".ju367vbf": { background: "var(--rk-colors-profileAction)" },
	".ju367vbg_hover": { background: "var(--rk-colors-profileAction)" },
	".ju367vbh_active": {
		background: "var(--rk-colors-profileAction)",
	},
	".ju367vbi": { background: "var(--rk-colors-profileActionHover)" },
	".ju367vbj_hover": {
		background: "var(--rk-colors-profileActionHover)",
	},
	".ju367vbk_active": {
		background: "var(--rk-colors-profileActionHover)",
	},
	".ju367vbl": { background: "var(--rk-colors-profileForeground)" },
	".ju367vbm_hover": {
		background: "var(--rk-colors-profileForeground)",
	},
	".ju367vbn_active": {
		background: "var(--rk-colors-profileForeground)",
	},
	".ju367vbo": {
		background: "var(--rk-colors-selectedOptionBorder)",
	},
	".ju367vbp_hover": {
		background: "var(--rk-colors-selectedOptionBorder)",
	},
	".ju367vbq_active": {
		background: "var(--rk-colors-selectedOptionBorder)",
	},
	".ju367vbr": { background: "var(--rk-colors-standby)" },
	".ju367vbs_hover": { background: "var(--rk-colors-standby)" },
	".ju367vbt_active": { background: "var(--rk-colors-standby)" },
	".ju367vbu": { borderColor: "var(--rk-colors-accentColor)" },
	".ju367vbv_hover": { borderColor: "var(--rk-colors-accentColor)" },
	".ju367vbw_active": { borderColor: "var(--rk-colors-accentColor)" },
	".ju367vbx": {
		borderColor: "var(--rk-colors-accentColorForeground)",
	},
	".ju367vby_hover": {
		borderColor: "var(--rk-colors-accentColorForeground)",
	},
	".ju367vbz_active": {
		borderColor: "var(--rk-colors-accentColorForeground)",
	},
	".ju367vc0": { borderColor: "var(--rk-colors-actionButtonBorder)" },
	".ju367vc1_hover": {
		borderColor: "var(--rk-colors-actionButtonBorder)",
	},
	".ju367vc2_active": {
		borderColor: "var(--rk-colors-actionButtonBorder)",
	},
	".ju367vc3": {
		borderColor: "var(--rk-colors-actionButtonBorderMobile)",
	},
	".ju367vc4_hover": {
		borderColor: "var(--rk-colors-actionButtonBorderMobile)",
	},
	".ju367vc5_active": {
		borderColor: "var(--rk-colors-actionButtonBorderMobile)",
	},
	".ju367vc6": {
		borderColor: "var(--rk-colors-actionButtonSecondaryBackground)",
	},
	".ju367vc7_hover": {
		borderColor: "var(--rk-colors-actionButtonSecondaryBackground)",
	},
	".ju367vc8_active": {
		borderColor: "var(--rk-colors-actionButtonSecondaryBackground)",
	},
	".ju367vc9": { borderColor: "var(--rk-colors-closeButton)" },
	".ju367vca_hover": { borderColor: "var(--rk-colors-closeButton)" },
	".ju367vcb_active": { borderColor: "var(--rk-colors-closeButton)" },
	".ju367vcc": {
		borderColor: "var(--rk-colors-closeButtonBackground)",
	},
	".ju367vcd_hover": {
		borderColor: "var(--rk-colors-closeButtonBackground)",
	},
	".ju367vce_active": {
		borderColor: "var(--rk-colors-closeButtonBackground)",
	},
	".ju367vcf": {
		borderColor: "var(--rk-colors-connectButtonBackground)",
	},
	".ju367vcg_hover": {
		borderColor: "var(--rk-colors-connectButtonBackground)",
	},
	".ju367vch_active": {
		borderColor: "var(--rk-colors-connectButtonBackground)",
	},
	".ju367vci": {
		borderColor: "var(--rk-colors-connectButtonBackgroundError)",
	},
	".ju367vcj_hover": {
		borderColor: "var(--rk-colors-connectButtonBackgroundError)",
	},
	".ju367vck_active": {
		borderColor: "var(--rk-colors-connectButtonBackgroundError)",
	},
	".ju367vcl": {
		borderColor: "var(--rk-colors-connectButtonInnerBackground)",
	},
	".ju367vcm_hover": {
		borderColor: "var(--rk-colors-connectButtonInnerBackground)",
	},
	".ju367vcn_active": {
		borderColor: "var(--rk-colors-connectButtonInnerBackground)",
	},
	".ju367vco": { borderColor: "var(--rk-colors-connectButtonText)" },
	".ju367vcp_hover": {
		borderColor: "var(--rk-colors-connectButtonText)",
	},
	".ju367vcq_active": {
		borderColor: "var(--rk-colors-connectButtonText)",
	},
	".ju367vcr": {
		borderColor: "var(--rk-colors-connectButtonTextError)",
	},
	".ju367vcs_hover": {
		borderColor: "var(--rk-colors-connectButtonTextError)",
	},
	".ju367vct_active": {
		borderColor: "var(--rk-colors-connectButtonTextError)",
	},
	".ju367vcu": {
		borderColor: "var(--rk-colors-connectionIndicator)",
	},
	".ju367vcv_hover": {
		borderColor: "var(--rk-colors-connectionIndicator)",
	},
	".ju367vcw_active": {
		borderColor: "var(--rk-colors-connectionIndicator)",
	},
	".ju367vcx": {
		borderColor: "var(--rk-colors-downloadBottomCardBackground)",
	},
	".ju367vcy_hover": {
		borderColor: "var(--rk-colors-downloadBottomCardBackground)",
	},
	".ju367vcz_active": {
		borderColor: "var(--rk-colors-downloadBottomCardBackground)",
	},
	".ju367vd0": {
		borderColor: "var(--rk-colors-downloadTopCardBackground)",
	},
	".ju367vd1_hover": {
		borderColor: "var(--rk-colors-downloadTopCardBackground)",
	},
	".ju367vd2_active": {
		borderColor: "var(--rk-colors-downloadTopCardBackground)",
	},
	".ju367vd3": { borderColor: "var(--rk-colors-error)" },
	".ju367vd4_hover": { borderColor: "var(--rk-colors-error)" },
	".ju367vd5_active": { borderColor: "var(--rk-colors-error)" },
	".ju367vd6": { borderColor: "var(--rk-colors-generalBorder)" },
	".ju367vd7_hover": {
		borderColor: "var(--rk-colors-generalBorder)",
	},
	".ju367vd8_active": {
		borderColor: "var(--rk-colors-generalBorder)",
	},
	".ju367vd9": { borderColor: "var(--rk-colors-generalBorderDim)" },
	".ju367vda_hover": {
		borderColor: "var(--rk-colors-generalBorderDim)",
	},
	".ju367vdb_active": {
		borderColor: "var(--rk-colors-generalBorderDim)",
	},
	".ju367vdc": { borderColor: "var(--rk-colors-menuItemBackground)" },
	".ju367vdd_hover": {
		borderColor: "var(--rk-colors-menuItemBackground)",
	},
	".ju367vde_active": {
		borderColor: "var(--rk-colors-menuItemBackground)",
	},
	".ju367vdf": { borderColor: "var(--rk-colors-modalBackdrop)" },
	".ju367vdg_hover": {
		borderColor: "var(--rk-colors-modalBackdrop)",
	},
	".ju367vdh_active": {
		borderColor: "var(--rk-colors-modalBackdrop)",
	},
	".ju367vdi": { borderColor: "var(--rk-colors-modalBackground)" },
	".ju367vdj_hover": {
		borderColor: "var(--rk-colors-modalBackground)",
	},
	".ju367vdk_active": {
		borderColor: "var(--rk-colors-modalBackground)",
	},
	".ju367vdl": { borderColor: "var(--rk-colors-modalBorder)" },
	".ju367vdm_hover": { borderColor: "var(--rk-colors-modalBorder)" },
	".ju367vdn_active": { borderColor: "var(--rk-colors-modalBorder)" },
	".ju367vdo": { borderColor: "var(--rk-colors-modalText)" },
	".ju367vdp_hover": { borderColor: "var(--rk-colors-modalText)" },
	".ju367vdq_active": { borderColor: "var(--rk-colors-modalText)" },
	".ju367vdr": { borderColor: "var(--rk-colors-modalTextDim)" },
	".ju367vds_hover": { borderColor: "var(--rk-colors-modalTextDim)" },
	".ju367vdt_active": {
		borderColor: "var(--rk-colors-modalTextDim)",
	},
	".ju367vdu": { borderColor: "var(--rk-colors-modalTextSecondary)" },
	".ju367vdv_hover": {
		borderColor: "var(--rk-colors-modalTextSecondary)",
	},
	".ju367vdw_active": {
		borderColor: "var(--rk-colors-modalTextSecondary)",
	},
	".ju367vdx": { borderColor: "var(--rk-colors-profileAction)" },
	".ju367vdy_hover": {
		borderColor: "var(--rk-colors-profileAction)",
	},
	".ju367vdz_active": {
		borderColor: "var(--rk-colors-profileAction)",
	},
	".ju367ve0": { borderColor: "var(--rk-colors-profileActionHover)" },
	".ju367ve1_hover": {
		borderColor: "var(--rk-colors-profileActionHover)",
	},
	".ju367ve2_active": {
		borderColor: "var(--rk-colors-profileActionHover)",
	},
	".ju367ve3": { borderColor: "var(--rk-colors-profileForeground)" },
	".ju367ve4_hover": {
		borderColor: "var(--rk-colors-profileForeground)",
	},
	".ju367ve5_active": {
		borderColor: "var(--rk-colors-profileForeground)",
	},
	".ju367ve6": {
		borderColor: "var(--rk-colors-selectedOptionBorder)",
	},
	".ju367ve7_hover": {
		borderColor: "var(--rk-colors-selectedOptionBorder)",
	},
	".ju367ve8_active": {
		borderColor: "var(--rk-colors-selectedOptionBorder)",
	},
	".ju367ve9": { borderColor: "var(--rk-colors-standby)" },
	".ju367vea_hover": { borderColor: "var(--rk-colors-standby)" },
	".ju367veb_active": { borderColor: "var(--rk-colors-standby)" },
	".ju367vec": { boxShadow: "var(--rk-shadows-connectButton)" },
	".ju367ved_hover": { boxShadow: "var(--rk-shadows-connectButton)" },
	".ju367vee_active": {
		boxShadow: "var(--rk-shadows-connectButton)",
	},
	".ju367vef": { boxShadow: "var(--rk-shadows-dialog)" },
	".ju367veg_hover": { boxShadow: "var(--rk-shadows-dialog)" },
	".ju367veh_active": { boxShadow: "var(--rk-shadows-dialog)" },
	".ju367vei": {
		boxShadow: "var(--rk-shadows-profileDetailsAction)",
	},
	".ju367vej_hover": {
		boxShadow: "var(--rk-shadows-profileDetailsAction)",
	},
	".ju367vek_active": {
		boxShadow: "var(--rk-shadows-profileDetailsAction)",
	},
	".ju367vel": { boxShadow: "var(--rk-shadows-selectedOption)" },
	".ju367vem_hover": {
		boxShadow: "var(--rk-shadows-selectedOption)",
	},
	".ju367ven_active": {
		boxShadow: "var(--rk-shadows-selectedOption)",
	},
	".ju367veo": { boxShadow: "var(--rk-shadows-selectedWallet)" },
	".ju367vep_hover": {
		boxShadow: "var(--rk-shadows-selectedWallet)",
	},
	".ju367veq_active": {
		boxShadow: "var(--rk-shadows-selectedWallet)",
	},
	".ju367ver": { boxShadow: "var(--rk-shadows-walletLogo)" },
	".ju367ves_hover": { boxShadow: "var(--rk-shadows-walletLogo)" },
	".ju367vet_active": { boxShadow: "var(--rk-shadows-walletLogo)" },
	".ju367veu": { color: "var(--rk-colors-accentColor)" },
	".ju367vev_hover": { color: "var(--rk-colors-accentColor)" },
	".ju367vew_active": { color: "var(--rk-colors-accentColor)" },
	".ju367vex": { color: "var(--rk-colors-accentColorForeground)" },
	".ju367vey_hover": {
		color: "var(--rk-colors-accentColorForeground)",
	},
	".ju367vez_active": {
		color: "var(--rk-colors-accentColorForeground)",
	},
	".ju367vf0": { color: "var(--rk-colors-actionButtonBorder)" },
	".ju367vf1_hover": { color: "var(--rk-colors-actionButtonBorder)" },
	".ju367vf2_active": {
		color: "var(--rk-colors-actionButtonBorder)",
	},
	".ju367vf3": { color: "var(--rk-colors-actionButtonBorderMobile)" },
	".ju367vf4_hover": {
		color: "var(--rk-colors-actionButtonBorderMobile)",
	},
	".ju367vf5_active": {
		color: "var(--rk-colors-actionButtonBorderMobile)",
	},
	".ju367vf6": {
		color: "var(--rk-colors-actionButtonSecondaryBackground)",
	},
	".ju367vf7_hover": {
		color: "var(--rk-colors-actionButtonSecondaryBackground)",
	},
	".ju367vf8_active": {
		color: "var(--rk-colors-actionButtonSecondaryBackground)",
	},
	".ju367vf9": { color: "var(--rk-colors-closeButton)" },
	".ju367vfa_hover": { color: "var(--rk-colors-closeButton)" },
	".ju367vfb_active": { color: "var(--rk-colors-closeButton)" },
	".ju367vfc": { color: "var(--rk-colors-closeButtonBackground)" },
	".ju367vfd_hover": {
		color: "var(--rk-colors-closeButtonBackground)",
	},
	".ju367vfe_active": {
		color: "var(--rk-colors-closeButtonBackground)",
	},
	".ju367vff": { color: "var(--rk-colors-connectButtonBackground)" },
	".ju367vfg_hover": {
		color: "var(--rk-colors-connectButtonBackground)",
	},
	".ju367vfh_active": {
		color: "var(--rk-colors-connectButtonBackground)",
	},
	".ju367vfi": {
		color: "var(--rk-colors-connectButtonBackgroundError)",
	},
	".ju367vfj_hover": {
		color: "var(--rk-colors-connectButtonBackgroundError)",
	},
	".ju367vfk_active": {
		color: "var(--rk-colors-connectButtonBackgroundError)",
	},
	".ju367vfl": {
		color: "var(--rk-colors-connectButtonInnerBackground)",
	},
	".ju367vfm_hover": {
		color: "var(--rk-colors-connectButtonInnerBackground)",
	},
	".ju367vfn_active": {
		color: "var(--rk-colors-connectButtonInnerBackground)",
	},
	".ju367vfo": { color: "var(--rk-colors-connectButtonText)" },
	".ju367vfp_hover": { color: "var(--rk-colors-connectButtonText)" },
	".ju367vfq_active": { color: "var(--rk-colors-connectButtonText)" },
	".ju367vfr": { color: "var(--rk-colors-connectButtonTextError)" },
	".ju367vfs_hover": {
		color: "var(--rk-colors-connectButtonTextError)",
	},
	".ju367vft_active": {
		color: "var(--rk-colors-connectButtonTextError)",
	},
	".ju367vfu": { color: "var(--rk-colors-connectionIndicator)" },
	".ju367vfv_hover": {
		color: "var(--rk-colors-connectionIndicator)",
	},
	".ju367vfw_active": {
		color: "var(--rk-colors-connectionIndicator)",
	},
	".ju367vfx": {
		color: "var(--rk-colors-downloadBottomCardBackground)",
	},
	".ju367vfy_hover": {
		color: "var(--rk-colors-downloadBottomCardBackground)",
	},
	".ju367vfz_active": {
		color: "var(--rk-colors-downloadBottomCardBackground)",
	},
	".ju367vg0": {
		color: "var(--rk-colors-downloadTopCardBackground)",
	},
	".ju367vg1_hover": {
		color: "var(--rk-colors-downloadTopCardBackground)",
	},
	".ju367vg2_active": {
		color: "var(--rk-colors-downloadTopCardBackground)",
	},
	".ju367vg3": { color: "var(--rk-colors-error)" },
	".ju367vg4_hover": { color: "var(--rk-colors-error)" },
	".ju367vg5_active": { color: "var(--rk-colors-error)" },
	".ju367vg6": { color: "var(--rk-colors-generalBorder)" },
	".ju367vg7_hover": { color: "var(--rk-colors-generalBorder)" },
	".ju367vg8_active": { color: "var(--rk-colors-generalBorder)" },
	".ju367vg9": { color: "var(--rk-colors-generalBorderDim)" },
	".ju367vga_hover": { color: "var(--rk-colors-generalBorderDim)" },
	".ju367vgb_active": { color: "var(--rk-colors-generalBorderDim)" },
	".ju367vgc": { color: "var(--rk-colors-menuItemBackground)" },
	".ju367vgd_hover": { color: "var(--rk-colors-menuItemBackground)" },
	".ju367vge_active": {
		color: "var(--rk-colors-menuItemBackground)",
	},
	".ju367vgf": { color: "var(--rk-colors-modalBackdrop)" },
	".ju367vgg_hover": { color: "var(--rk-colors-modalBackdrop)" },
	".ju367vgh_active": { color: "var(--rk-colors-modalBackdrop)" },
	".ju367vgi": { color: "var(--rk-colors-modalBackground)" },
	".ju367vgj_hover": { color: "var(--rk-colors-modalBackground)" },
	".ju367vgk_active": { color: "var(--rk-colors-modalBackground)" },
	".ju367vgl": { color: "var(--rk-colors-modalBorder)" },
	".ju367vgm_hover": { color: "var(--rk-colors-modalBorder)" },
	".ju367vgn_active": { color: "var(--rk-colors-modalBorder)" },
	".ju367vgo": { color: "var(--rk-colors-modalText)" },
	".ju367vgp_hover": { color: "var(--rk-colors-modalText)" },
	".ju367vgq_active": { color: "var(--rk-colors-modalText)" },
	".ju367vgr": { color: "var(--rk-colors-modalTextDim)" },
	".ju367vgs_hover": { color: "var(--rk-colors-modalTextDim)" },
	".ju367vgt_active": { color: "var(--rk-colors-modalTextDim)" },
	".ju367vgu": { color: "var(--rk-colors-modalTextSecondary)" },
	".ju367vgv_hover": { color: "var(--rk-colors-modalTextSecondary)" },
	".ju367vgw_active": {
		color: "var(--rk-colors-modalTextSecondary)",
	},
	".ju367vgx": { color: "var(--rk-colors-profileAction)" },
	".ju367vgy_hover": { color: "var(--rk-colors-profileAction)" },
	".ju367vgz_active": { color: "var(--rk-colors-profileAction)" },
	".ju367vh0": { color: "var(--rk-colors-profileActionHover)" },
	".ju367vh1_hover": { color: "var(--rk-colors-profileActionHover)" },
	".ju367vh2_active": {
		color: "var(--rk-colors-profileActionHover)",
	},
	".ju367vh3": { color: "var(--rk-colors-profileForeground)" },
	".ju367vh4_hover": { color: "var(--rk-colors-profileForeground)" },
	".ju367vh5_active": { color: "var(--rk-colors-profileForeground)" },
	".ju367vh6": { color: "var(--rk-colors-selectedOptionBorder)" },
	".ju367vh7_hover": {
		color: "var(--rk-colors-selectedOptionBorder)",
	},
	".ju367vh8_active": {
		color: "var(--rk-colors-selectedOptionBorder)",
	},
	".ju367vh9": { color: "var(--rk-colors-standby)" },
	".ju367vha_hover": { color: "var(--rk-colors-standby)" },
	".ju367vhb_active": { color: "var(--rk-colors-standby)" },
	"@media screen and (min-width: 768px)": {
		__expression__: "screen and (min-width: 768px)",
		".ju367v1": { alignItems: "flex-start" },
		".ju367v3": { alignItems: "flex-end" },
		".ju367v5": { alignItems: "center" },
		".ju367v7": { display: "none" },
		".ju367v9": { display: "block" },
		".ju367vb": { display: "flex" },
		".ju367vd": { display: "inline" },
		"._1ckjpok1": { width: "360px" },
		"._1ckjpok2": { width: "480px" },
		"._1ckjpok3": { width: "720px" },
		"._1ckjpok4": { minWidth: "368px", width: "368px" },
		"._1vwt0cg3": { minWidth: "287px" },
	},
	"._12cbo8i3": { "-_12cbo8i0": "1", "-_12cbo8i1": "1" },
	"._12cbo8i3__after": { "-_12cbo8i0": "1", "-_12cbo8i1": "1" },
	"._12cbo8i3_hover": { transform: "scale(var(--_12cbo8i0))" },
	"._12cbo8i3_active": { transform: "scale(var(--_12cbo8i1))" },
	"._12cbo8i3_active__after": {
		content: '""',
		bottom: "-1px",
		display: "block",
		left: "-1px",
		position: "absolute",
		right: "-1px",
		top: "-1px",
		transform: "scale(calc((1 / var(--_12cbo8i1)) * var(--_12cbo8i0)))",
	},
	"._12cbo8i4": { "-_12cbo8i0": "1.025" },
	"._12cbo8i4__after": { "-_12cbo8i0": "1.025" },
	"._12cbo8i5": { "-_12cbo8i0": "1.1" },
	"._12cbo8i5__after": { "-_12cbo8i0": "1.1" },
	"._12cbo8i6": { "-_12cbo8i1": "0.95" },
	"._12cbo8i6__after": { "-_12cbo8i1": "0.95" },
	"._12cbo8i7": { "-_12cbo8i1": "0.9" },
	"._12cbo8i7__after": { "-_12cbo8i1": "0.9" },
	"._1luule42": {
		WebkitAnimation: "_1luule41 3s infinite linear",
		animation: "_1luule41 3s infinite linear",
	},
	"._1luule43": {
		background:
			"conic-gradient(from 180deg at 50% 50%, rgba(72, 146, 254, 0) 0deg, currentColor 282.04deg, rgba(72, 146, 254, 0) 319.86deg, rgba(72, 146, 254, 0) 360deg)",
		height: "21px",
		width: "21px",
	},
	"._9pm4ki3": {
		WebkitAnimation: "_9pm4ki1 150ms ease",
		animation: "_9pm4ki1 150ms ease",
		bottom: "-200px",
		left: "-200px",
		padding: "200px",
		right: "-200px",
		top: "-200px",
		transform: "translateZ(0)",
		zIndex: "2147483646",
	},
	"._9pm4ki5": {
		WebkitAnimation:
			"_9pm4ki0 350ms cubic-bezier(.15, 1.15, 0.6, 1.00), _9pm4ki1 150ms ease",
		animation:
			"_9pm4ki0 350ms cubic-bezier(.15, 1.15, 0.6, 1.00), _9pm4ki1 150ms ease",
		maxWidth: "100vw",
	},
	"._1ckjpok1": {
		boxSizing: "content-box",
		maxWidth: "100vw",
		width: "360px",
	},
	"._1ckjpok2": { width: "100vw" },
	"._1ckjpok3": { width: "768px" },
	"._1ckjpok4": { minWidth: "368px", width: "368px" },
	"._1ckjpok6": {
		borderWidth: "0px",
		boxSizing: "border-box",
		width: "100vw",
	},
	"@media screen and (max-width: 767px)": {
		__expression__: "screen and (max-width: 767px)",
		"._1ckjpok7": {
			borderBottomLeftRadius: "0",
			borderBottomRightRadius: "0",
			marginTop: "-200px",
			paddingBottom: "200px",
			top: "200px",
		},
	},
	".v9horb0_hover": { background: "unset" },
	".g5kl0l0": { borderColor: "transparent" },
	"._1vwt0cg0": { background: "white" },
	"._1vwt0cg2": { maxHeight: "454px", overflowY: "auto" },
	"._1vwt0cg3": { minWidth: "246px" },
	"._1vwt0cg4": { minWidth: "100%" },
	"._1am14410": {
		overflow: "auto",
		scrollbarWidth: "none",
		transform: "translateZ(0)",
	},
	"._1am14410___webkit_scrollbar": { display: "none" },
};
